# config

filter_domains = '''
.163jiasu.com
.1test.cn
.21okglb.cn
.21vianet.com.cn
.21vokglb.cn
.360cdn.cn
.360qhcdn.com
.360wzb.cn
.360wzb.com
.51cdn.com
.5test.cn
.acadn.com
.afxcdn.net
.aicdn.com
.akadns.net
.akamai.
.akamai.com
.akamaiedge.net
.akamai.net
.akamai-staging.net
.akamaitech.net
.akamaitechnologies.com
.akamaized.net
.alicdn.com
.alicloudlayer.com
.alicloudsec.com
.alikunlun.com
.alikunlun.net
.alivecdn.com
.aliyuncs.com
.aliyun-inc.com
.amazonaws.com
.aodianyun.com
.aqb.so
.att-dsa.net
.awsdns
.ay1.b.yahoo.com
.azureedge.
.azureedge.net
.b2r.com.cn
.baiduyundns.cn
.baiduyundns.com
.baiduyundns.net
.bcedns.cn
.bcedns.com
.bcedns.net
.bdydns.cn
.bdydns.com
.bdydns.net
.bitgravity.
.bitgravity.com
.bluehatnetwork.com
.blueit.com
.blueit.org.cn
.bsclink.cn
.c3cache.net
.c3cdn.net
.cachecn.com
.cachecn.net
.cachefly.
.cachefly.net
.cap-mii.net
.cc-1.com
.ccbench.com
.cc-cps.cn
.cc-cps.com
.cc-cps.com.cn
.cc-cps.mobi
.cc-cps.net
.ccgslb.cn
.ccgslb.com
.ccgslb.com.cn
.ccgslb.net
.ccgslb.net.cn
.ccindex.cn
.ccindex.com.cn
.ccmplus.cn
.ccmplus.com.cn
.ccmplus.net
.cdn2cdn.net
.cdn77.net
.cdn77.org
.cdn.bitgravity.com
.cdn.cloudflare.net
.cdnetworks.net
.cdngc.net
.cdngslb.com
.cdnhwc2.com
.cdnify.io
.cdn.qshyy.cn
.cdnsun.net
.cdnsvc.cn
.cdnsvc.com
.cdnsvc.com.cn
.cdnsvc.net
.cdnsvc.net.cn
.cdn.telefonica.com
.cdntip.com
.cdnudns.com
.chinacache.com
.chinacache.com.cn
.chinacache.net
.chinacache.org
.chinacdnweb.qiniu.com
.chinaidns.net
.chinanetcenter.com
.clients.turbobytes.net
.cloudcdn.cn
.cloudcdn.net
.clouddn.com
.cloudflare
.cloudflare.com
.cloudfront.
.cloudfront.net
.cloudglb.com
.cloudglb.net
.cloudtcp.net
.cloudxns.com
.cloudxns.net
.cncssr.chinacache.net
.customcdn.cn
.customcdn.com
.dnion.com
.dnspao.com
.dnsv1.
.dnsv1.com
.dwion.com
.edgecast.
.edgecastcdn.net
.edgekey.
.edgekey.net
.edgesuite.net
.ewcache.com
.fastcache.com
.fastcdn.com
.fastly.
.fastlylb.net
.fastly.net
.fastwebcdn.com
.fastweb.com.cn
.ffdns.net
.footprint.
.footprint.net
.fpbns.
.fpbns.net
.fsspace.cn
.fsspace.com
.fsspace.com.cn
.fwcdn.com
.fwcdn.net
.fwdns.net
.fwmob.com
.gccdn.cn
.gccdn.net
.globalcdn.cn
.googlesyndication.
.googleusercontent.com
.gslbsvc.cn
.gslbsvc.com
.gslbsvc.com.cn
.gslbsvc.net
.gslbsvc.net.cn
.gslb.taobao.com
.gslb.tbcache.com
.hacdn.com
.hacdn.net
.hadns.net
.hd-cdn.com
.hdslb.com
.hdslb.net
.hiberniacdn.com
.hichina.com
.hichina.net
.hwcdn.net
.ialicdn.com
.igslb.net
.incapdns.
.incapdns.net
.inscname.net
.insnw.net
.instacontent.net
.jcloud-cdn.com
.jiashule.com
.jiasule.org
.jomodns.com
.ks-cdn1.com
.ksyuncdn.com
.kunlunaq.com
.kunlunar.com
.kunlunca.com
.kunluncan.com
.kunlun.com
.kunlunea.com
.kunlungem.com
.kunlungr.com
.kunlunhuf.com
.kunlunle.com
.kunlunli.com
.kunlunno.com
.kunlunpi.com
.kunlunra.com
.kunlunsa.com
.kunlunsc.com
.kunlunsl.com
.kunlunso.com
.kunlunta.com
.kunlunvi.com
.kunlunwe.com
.kxcdn.com
.l.doubleclick.net
.letvcdn.com
.lldns.net
.llnwd.
.llnwd.net
.lswcdn.net
.lxdns.com
.lxdns.net
.lxsvc.cn
.lxsvc.net
.mirror-image.net
.mncdn.com
.mschcdn.com
.mwcloudcdn.com
.myalicdn.com
.myxns.cn
.myxns.com.cn
.myxns.net.cn
.myxns.org
.netcenter.com.cn
.netdna.
.netdna-cdn.com
.netdna.com
.netdna-ssl.com
.newdefend.cn
.newdefend.com
.newdefend.com.cn
.newdefend.net
.newdefend.net.cn
.newdefend.org
.newdefend.org.cn
.ngenix.
.okglb.com
.ourglb0.com
.ourwebat.com
.ourwebcdn.com
.ourwebcdn.net
.ourwebpic.com
.panthercdn.com
.pilidns.com
.qbox.me
.qihucdn.com
.qingcdn.com
.qiniudn.com
.qiniudns.com
.rncdn1.com
.shifen.com
.simplecdn.net
.spcdntip.com
.spdydns.com
.speedcdns.com
.speedupchina.com
.speedupchina.net
.stackpathdns.com
.swiftcdn1.com
.swiftserve.com
.sz-dns.net
.tbcache.com
.tc.cdntip.com
.tcdn.qq.com
.tcloudscdn.com
.tdnsv8.com
.telefonica.
.tlgslb.com
.trpcdn.net
.txcdn.cn
.txnetworks.cn
.ucloud.cn
.unicache.com
.verycdn.net
.verygslb.com
.vo.llnwd.net
.vo.msecnd.net
.wangsu.com
.webluker.com
.wscdns.com
.wscloudcdn.com
.wsdvs.com
.wsglb0.com
.wsngb.com
.xgslb.net
.yunjiasu-cdn.net
.zenedge.net
.dns.com
'''.strip('\n').split('\n')


filter_hosts = '''
223.5.5.5
223.6.6.6
114.114.114.114
114.114.115.115
180.76.76.76
119.29.29.29
182.254.116.116
8.8.8.8
8.8.4.4
9.9.9.9
9.9.9.10
149.112.112.112
4.2.2.1
4.2.2.2
4.2.2.3
4.2.2.4
4.2.2.5
4.2.2.6
1.1.1.1
1.0.0.1
1.0.0.2
1.0.0.3
1.0.0.19
208.67.222.222
208.67.220.220
8.26.56.26
8.20.247.20
84.200.69.80
84.200.70.40
185.228.168.9
185.228.169.9
64.6.64.6
64.6.65.6
198.101.242.72
23.253.163.53
176.103.130.130
176.103.130.131
'''.strip('\n').split('\n')


top_sufix = 'bj.cn|tj.cn|sh.cn|cq.cn|he.cn|sx.cn|nm.cn|ln.cn|jl.cn|hl.cn|js.cn|zj.cn|ah.cn|fj.cn|jx.cn|sd.cn|ha.cn|hb.cn|hn.cn|gd.cn|gx.cn|hi.cn|sc.cn|gz.cn|yn.cn|xz.cn|sn.cn|gs.cn|qh.cn|nx.cn|xj.cn|tw.cn|hk.cn|mo.cn|gov.cn|net.cn|org.cn|ac.cn|mil.cn|edu.cn|com.cn|政务.cn|公益.cn|edu.tw|gov.tw|mil.tw|com.tw|net.tw|org.tw|idv.tw|game.tw|ebiz.tw|club.tw|cc|vip|top|aero|arpa|asia|biz|cat|com|coop|edu|gov|int|info|jobs|mil|mobi|museum|name|net|org|pro|tel|trave|digital|run|aarp|abarth|abb|abbott|abbvie|abc|able|abogado|abudhabi|ac|academy|accenture|accountant|accountants|aco|active|actor|ad|adac|ads|adult|ae|aeg|aetna|af|afamilycompany|afl|africa|ag|agakhan|agency|ai|aig|aigo|airbus|airforce|airtel|akdn|al|alfaromeo|alibaba|alipay|allfinanz|allstate|ally|alsace|alstom|am|amazon|americanexpress|americanfamily|amex|amfam|amica|amsterdam|an|analytics|android|anquan|anz|ao|aol|apartments|app|apple|aq|aquarelle|ar|arab|aramco|archi|army|art|arte|as|asda|associates|at|athleta|attorney|au|auction|audi|audible|audio|auspost|author|auto|autos|avianca|aw|aws|ax|axa|az|azure|ba|baby|baidu|banamex|bananarepublic|band|bank|bar|barcelona|barclaycard|barclays|barefoot|bargains|baseball|basketball|bauhaus|bayern|bb|bbc|bbt|bbva|bcg|bcn|bd|be|beats|beauty|beer|bentley|berlin|best|bestbuy|bet|bf|bg|bh|bharti|bi|bible|bid|bike|bing|bingo|bio|bj|bl|black|blackfriday|blanco|blockbuster|blog|bloomberg|blue|bm|bms|bmw|bn|bnl|bnpparibas|bo|boats|boehringer|bofa|bom|bond|boo|book|booking|boots|bosch|bostik|boston|bot|boutique|box|bq|br|bradesco|bridgestone|broadway|broker|brother|brussels|bs|bt|budapest|bugatti|build|builders|business|buy|buzz|bv|bw|by|bz|bzh|ca|cab|cafe|cal|call|calvinklein|cam|camera|camp|cancerresearch|canon|capetown|capital|capitalone|car|caravan|cards|care|career|careers|cars|cartier|casa|case|caseih|cash|casino|catering|catholic|cba|cbn|cbre|cbs|cd|ceb|center|ceo|cern|cf|cfa|cfd|cg|ch|chanel|channel|charity|chase|chat|cheap|chintai|chloe|christmas|chrome|chrysler|church|ci|cipriani|circle|cisco|citadel|citi|citic|city|cityeats|ck|cl|claims|cleaning|click|clinic|clinique|clothing|cloud|club|clubmed|cm|cn|co|coach|codes|coffee|college|cologne|comcast|commbank|community|company|compare|computer|comsec|condos|construction|consulting|contact|contractors|cooking|cookingchannel|cool|corsica|country|coupon|coupons|courses|cpa|cr|credit|creditcard|creditunion|cricket|crown|crs|cruise|cruises|csc|cu|cuisinella|cv|cw|cx|cy|cymru|cyou|cz|dabur|dad|dance|data|date|dating|datsun|day|dclk|dds|de|deal|dealer|deals|degree|delivery|dell|deloitte|delta|democrat|dental|dentist|desi|design|dev|dhl|diamonds|diet|direct|directory|discount|discover|dish|diy|dj|dk|dm|dnp|do|docs|doctor|dodge|dog|doha|domains|doosan|dot|download|drive|dtv|dubai|duck|dunlop|duns|dupont|durban|dvag|dvr|dz|earth|eat|ec|eco|edeka|education|ee|eg|eh|email|emerck|energy|engineer|engineering|enterprises|epost|epson|equipment|er|ericsson|erni|es|esq|estate|esurance|et|etisalat|eu|eurovision|eus|events|everbank|exchange|expert|exposed|express|extraspace|fage|fail|fairwinds|faith|family|fan|fans|farm|farmers|fashion|fast|fedex|feedback|ferrari|ferrero|fi|fiat|fidelity|fido|film|final|finance|financial|fire|firestone|firmdale|fish|fishing|fit|fitness|fj|fk|flickr|flights|flir|florist|flowers|flsmidth|fly|fm|fo|foo|food|foodnetwork|football|ford|forex|forsale|forum|foundation|fox|fr|free|fresenius|frl|frogans|frontdoor|frontier|ftr|fujitsu|fujixerox|fun|fund|furniture|futbol|fyi|ga|gal|gallery|gallo|gallup|game|games|gap|garden|gay|gb|gbiz|gd|gdn|ge|gea|gent|genting|george|gf|gg|ggee|gh|gi|gift|gifts|gives|giving|gl|glade|glass|gle|global|globo|gm|gmail|gmbh|gmo|gmx|gn|godaddy|gold|goldpoint|golf|goo|goodhands|goodyear|goog|google|gop|got|gp|gq|gr|grainger|graphics|gratis|green|gripe|grocery|group|gs|gt|gu|guardian|gucci|guge|guide|guitars|guru|gw|gy|hair|hamburg|hangout|haus|hbo|hdfc|hdfcbank|health|healthcare|help|helsinki|here|hermes|hgtv|hiphop|hisamitsu|hitachi|hiv|hk|hkt|hm|hn|hockey|holdings|holiday|homedepot|homegoods|homes|homesense|honda|honeywell|horse|hospital|host|hosting|hot|hoteles|hotels|hotmail|house|how|hr|hsbc|ht|htc|hu|hughes|hyatt|hyundai|ibm|icbc|ice|icu|id|ie|ieee|ifm|iinet|ikano|il|im|imamat|imdb|immo|immobilien|in|inc|industries|infiniti|ing|ink|institute|insurance|insure|intel|international|intuit|investments|io|ipiranga|iq|ir|irish|is|iselect|ismaili|ist|istanbul|it|itau|itv|iveco|iwc|jaguar|java|jcb|jcp|je|jeep|jetzt|jewelry|jio|jlc|jll|jm|jmp|jnj|jo|joburg|jot|joy|jp|jpmorgan|jprs|juegos|juniper|kaufen|kddi|ke|kerryhotels|kerrylogistics|kerryproperties|kfh|kg|kh|ki|kia|kim|kinder|kindle|kitchen|kiwi|km|kn|koeln|komatsu|kosher|kp|kpmg|kpn|kr|krd|kred|kuokgroup|kw|ky|kyoto|kz|la|lacaixa|ladbrokes|lamborghini|lamer|lancaster|lancia|lancome|land|landrover|lanxess|lasalle|lat|latino|latrobe|law|lawyer|lb|lc|lds|lease|leclerc|lefrak|legal|lego|lexus|lgbt|li|liaison|lidl|life|lifeinsurance|lifestyle|lighting|like|lilly|limited|limo|lincoln|linde|link|lipsy|live|living|lixil|lk|llc|llp|loan|loans|locker|locus|loft|lol|london|lotte|lotto|love|lpl|lplfinancial|lr|ls|lt|ltd|ltda|lu|lundbeck|lupin|luxe|luxury|lv|ly|ma|macys|madrid|maif|maison|makeup|man|management|mango|map|market|marketing|markets|marriott|marshalls|maserati|mattel|mba|mc|mcd|mcdonalds|mckinsey|md|me|med|media|meet|melbourne|meme|memorial|men|menu|meo|merckmsd|metlife|mf|mg|mh|miami|microsoft|mini|mint|mit|mitsubishi|mk|ml|mlb|mls|mm|mma|mn|mo|mobile|mobily|moda|moe|moi|mom|monash|money|monster|montblanc|mopar|mormon|mortgage|moscow|moto|motorcycles|mov|movie|movistar|mp|mq|mr|ms|msd|mt|mtn|mtpc|mtr|mu|mutual|mutuelle|mv|mw|mx|my|mz|na|nab|nadex|nagoya|nationwide|natura|navy|nba|nc|ne|nec|netbank|netflix|network|neustar|new|newholland|news|next|nextdirect|nexus|nf|nfl|ng|ngo|nhk|ni|nico|nike|nikon|ninja|nissan|nissay|nl|no|nokia|northwesternmutual|norton|now|nowruz|nowtv|np|nr|nra|nrw|ntt|nu|nyc|nz|obi|observer|off|office|okinawa|olayan|olayangroup|oldnavy|ollo|om|omega|one|ong|onl|online|onyourside|ooo|open|oracle|orange|organic|orientexpress|origins|osaka|otsuka|ott|ovh|pa|page|pamperedchef|panasonic|panerai|paris|pars|partners|parts|party|passagens|pay|pccw|pe|pet|pf|pfizer|pg|ph|pharmacy|phd|philips|phone|photo|photography|photos|physio|piaget|pics|pictet|pictures|pid|pin|ping|pink|pioneer|pizza|pk|pl|place|play|playstation|plumbing|plus|pm|pn|pnc|pohl|poker|politie|porn|post|pr|pramerica|praxi|press|prime|prod|productions|prof|progressive|promo|properties|property|protection|pru|prudential|ps|pt|pub|pw|pwc|py|qa|qpon|quebec|quest|qvc|racing|radio|raid|re|read|realestate|realtor|realty|recipes|red|redstone|redumbrella|rehab|reise|reisen|reit|reliance|ren|rent|rentals|repair|report|republican|rest|restaurant|review|reviews|rexroth|rich|richardli|ricoh|rightathome|ril|rio|rip|rmit|ro|rocher|rocks|rodeo|rogers|room|rs|rsvp|ru|rugby|ruhr|rw|rwe|ryukyu|sa|saarland|safe|safety|sakura|sale|salon|samsclub|samsung|sandvik|sandvikcoromant|sanofi|sap|sapo|sarl|sas|save|saxo|sb|sbi|sbs|sc|sca|scb|schaeffler|schmidt|scholarships|school|schule|schwarz|science|scjohnson|scor|scot|sd|se|search|seat|secure|security|seek|select|sener|services|ses|seven|sew|sex|sexy|sfr|sg|sh|shangrila|sharp|shaw|shell|shia|shiksha|shoes|shop|shopping|shouji|show|showtime|shriram|si|silk|sina|singles|site|sj|sk|ski|skin|sky|skype|sl|sling|sm|smart|smile|sn|sncf|so|soccer|social|softbank|software|sohu|solar|solutions|song|sony|soy|spa|space|spiegel|sport|spot|spreadbetting|sr|srl|srt|ss|st|stada|staples|star|starhub|statebank|statefarm|statoil|stc|stcgroup|stockholm|storage|store|stream|studio|study|style|su|sucks|supplies|supply|support|surf|surgery|suzuki|sv|swatch|swiftcover|swiss|sx|sy|sydney|symantec|systems|sz|tab|taipei|talk|taobao|target|tatamotors|tatar|tattoo|tax|taxi|tc|tci|td|tdk|team|tech|technology|telecity|telefonica|temasek|tennis|teva|tf|tg|th|thd|theater|theatre|tiaa|tickets|tienda|tiffany|tips|tires|tirol|tj|tjmaxx|tjx|tk|tkmaxx|tl|tm|tmall|tn|to|today|tokyo|tools|toray|toshiba|total|tours|town|toyota|toys|tp|tr|trade|trading|training|travel|travelchannel|travelers|travelersinsurance|trust|trv|tt|tube|tui|tunes|tushu|tv|tvs|tw|tz|ua|ubank|ubs|uconnect|ug|uk|um|unicom|university|uno|uol|ups|us|uy|uz|va|vacations|vana|vanguard|vc|ve|vegas|ventures|verisign|versicherung|vet|vg|vi|viajes|video|vig|viking|villas|vin|virgin|visa|vision|vista|vistaprint|viva|vivo|vlaanderen|vn|vodka|volkswagen|volvo|vote|voting|voto|voyage|vu|vuelos|wales|walmart|walter|wang|wanggou|warman|watch|watches|weather|weatherchannel|webcam|weber|website|wed|wedding|weibo|weir|wf|whoswho|wien|wiki|williamhill|win|windows|wine|winners|wme|wolterskluwer|woodside|work|works|world|wow|ws|wtc|wtf|xbox|xerox|xfinity|xihuan|xin|测试|कॉम|परीक्षा|セール|佛山|ಭಾರತ|慈善|集团|在线|한국|ଭାରତ|大众汽车|点看|คอม|ভাৰত|ভারত|八卦|ישראל|موقع|বাংলা|公益|公司|香格里拉|网站|移动|我爱你|москва|испытание|қаз|католик|онлайн|сайт|联通|срб|бг|бел|קום|时尚|微博|테스트|淡马锡|ファッション|орг|नेट|ストア|アマゾン|삼성|சிங்கப்பூர்|商标|商店|商城|дети|мкд|טעסט|ею|ポイント|新闻|工行|家電|كوم|中文网|中信|中国|中國|娱乐|谷歌|భారత్|ලංකා|電訊盈科|购物|測試|クラウド|ભારત|通販|भारतम्|भारत|भारोत|آزمایشی|பரிட்சை|网店|संगठन|餐厅|网络|ком|укр|香港|亚马逊|诺基亚|食品|δοκιμή|飞利浦|إختبار|台湾|台灣|手表|手机|мон|الجزائر|عمان|ارامكو|ایران|العليان|اتصالات|امارات|بازار|موريتانيا|پاکستان|الاردن|موبايلي|بارت|بھارت|المغرب|ابوظبي|البحرين|السعودية|ڀارت|كاثوليك|سودان|همراه|عراق|مليسيا|澳門|닷컴|政府|شبكة|بيتك|عرب|გე|机构|组织机构|健康|ไทย|سورية|招聘|рус|рф|珠宝|تونس|大拿|ລາວ|みんな|グーグル|ευ|ελ|世界|書籍|ഭാരതം|ਭਾਰਤ|网址|닷넷|コム|天主教|游戏|vermögensberater|vermögensberatung|企业|信息|嘉里大酒店|嘉里|مصر |قطر|广东|இலங்கை|இந்தியா|հայ|新加坡|فلسطين|テスト|政务|xperia|xyz|yachts|yahoo|yamaxun|yandex|ye|yodobashi|yoga|yokohama|you|youtube|yt|yun|za|zappos|zara|zero|zip|zippo|zm|zone|zuerich|zw'

#cn_sufix = 'ac.cn|ah.cn|bj.cn|com.cn|cq.cn|fj.cn|gd.cn|gov.cn|gs.cn|gx.cn|gz.cn|ha.cn|hb.cn|he.cn|hi.cn|hk.cn|hl.cn|hn.cn|jl.cn|js.cn|jx.cn|ln.cn|mo.cn|net.cn|nm.cn|nx.cn|org.cn|edu.cn|'

# .ac|.ad|.ae|.af|.ag|.ai|.al|.am|.an|.ao|.aq|.ar|.as|.at|.au|.aw|.az|.ba|.bb|.bd|.be|.bf|.bg|.bh|.bi|.bj|.bm|.bn|.bo|.br|.bs|.bt|.bv|.bw|.by|.bz|.ca|.cc|.cd|.cf|.cg|.ch|.ci|.ck|.cl|.cm|.cn|.co|.cr|.cu|.cv|.cx|.cy|.cz|.de|.dj|.dk|.dm|.do|.dz|.ec|.ee|.eg|.eh|.er|.es|.et|.eu|.fi|.fj|.fk|.fm|.fo|.fr|.ga|.gd|.ge|.gf|.gg|.gh|.gi|.gl|.gm|.gn|.gp|.gq|.gr|.gs|.gt|.gu|.gw|.gy|.hk|.hm|.hn|.hr|.ht|.hu|.id|.ie|.il|.im|.in|.io|.iq|.ir|.is|.it|.je|.jm|.jo|.jp|.ke|.kg|.kh|.ki|.km|.kn|.kp|.kr|.kw|.ky|.kz|.la|.lb|.lc|.li|.lk|.lr|.ls|.lt|.lu|.lv|.ly|.ma|.mc|.md|.me|.mg|.mh|.mk|.ml|.mm|.mn|.mo|.mp|.mq|.mr|.ms|.mt|.mu|.mv|.mw|.mx|.my|.mz|.na|.nc|.ne|.nf|.ng|.ni|.nl|.no|.np|.nr|.nu|.nz|.om|.pa|.pe|.pf|.pg|.ph|.pk|.pl|.pm|.pn|.pr|.ps|.pt|.pw|.py|.qa|.re|.ro|.ru|.rw|.sa|.sb|.sc|.sd|.se|.sg|.sh|.si|.sj|.sk|.sl|.sm|.sn|.so|.sr|.st|.sv|.sy|.sz|.tc|.td|.tf|.tg|.th|.tj|.tk|.tl|.tm|.tn|.to|.tp|.tr|.tt|.tv|.tw|.tz|.ua|.ug|.uk|.um|.us|.uy|.uz|.va|.vc|.ve|.vg|.vi|.vn|.vu|.wf|.ws|.ye|.yr|.yt|.yu|.za|.zm|.zw
# country_sufix = 'ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cu|cv|cx|cy|cz|de|dj|dk|dm|do|dz|ec|ee|eg|eh|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|sk|sl|sm|sn|so|sr|st|sv|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|um|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yr|yt|yu|za|zm|zw'
country_sufix = 'cn|co|jo|jp|ke|kg|mz|mx|ug|uk'

file_upload_package = '''
### File upload format data
### Copy and paste on burpsuite

```
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryzKD4Hm0eKYto9ERE
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.5790.171 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Connection: close
Content-Length: 277

------WebKitFormBoundaryzKD4Hm0eKYto9ERE
Content-Disposition: form-data; name="x"


------WebKitFormBoundaryzKD4Hm0eKYto9ERE
Content-Disposition: form-data; name="filename"; filename="x.png"
Content-Type: image/png

test
------WebKitFormBoundaryzKD4Hm0eKYto9ERE--
```
'''

